package persistence.sql.ddl.entitymanager;

import jdbc.JdbcTemplate;
import jdbc.RowMapper;
import org.jetbrains.annotations.NotNull;
import persistence.sql.ddl.EntityTable;
import persistence.sql.ddl.FieldUtils;
import persistence.sql.ddl.generator.*;

import java.lang.reflect.Field;
import java.sql.*;
import java.util.List;

public class DefaultEntityManager implements EntityManager {
    private final Connection connection;
    private final JdbcTemplate jdbcTemplate;
    private final InsertDMLGenerator insertDMLGenerator;
    private final UpdateDMLGenerator updateDMLGenerator;
    private final SelectDMLGenerator selectDMLGenerator;
    private final DeleteDMLGenerator deleteDMLGenerator;

    public DefaultEntityManager(Connection connection) {
        this.connection = connection;
        this.jdbcTemplate = new JdbcTemplate(connection);
        this.insertDMLGenerator = new DefaultInsertDMLGenerator();
        this.updateDMLGenerator = new DefaultUpdateDMLGenerator();
        this.selectDMLGenerator = new DefaultSelectDMLGenerator();
        this.deleteDMLGenerator = new DefaultDeleteDMLGenerator();
    }

    @Override
    public <T> T persist(T entity) {
        return null;
    }

    @Override
    public <T> T find(Class<T> clazz, Object id) {
        return  null;
    }

    private <T> Object insert(T entity, int autoGeneratedKeys) {
        return null;
    }

    private <T> void update(T entity) {
    }

    @Override
    public <T> void remove(T entity) {
    }

    @NotNull
    private <T> RowMapper<T> toObject(EntityTable entityTable) {
        return resultSet -> {
            T entity = (T) entityTable.newInstance();

            entityTable.getAllColumnNames().forEach(it -> {
                Field field = entityTable.getFieldByColumnName(it);

                applyValue(resultSet, it, field, entity);
            });

            return entity;
        };
    }

    private <T> void applyValue(ResultSet resultSet, String it, Field field, T entity) {
        try {
            Object value = resultSet.getObject(it);

            FieldUtils.setValue(field, entity, value);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
